
title: "Jitika Rajpoot"
email: "your-email@example.com"
description: "Personal academic website"
baseurl: ""
url: "https://JitikaR.github.io"
theme: minimal

navigation:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv/
  - title: "Research"
    url: /research/
  - title: "Publications"
    url: /publications/
  - title: "Get to Know Me"
    url: /get-to-know-me/
